name = "Genqo"
uuid = "4075d74c-027e-4884-b5ac-9f01362c98ed"
version = "0.1.0"
authors = ["Jacob Gunnell <jacob.r.gunnell@gmail.com>"]

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockDiagonals = "0a1fb500-61f7-11e9-3c65-f5ef3456f9f0"
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Nemo = "2edaba10-b0f1-5616-af89-8c11ac63239a"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
BenchmarkTools = "1.6.3"
BlockArrays = "1.9.3"
BlockDiagonals = "0.2.0"
Debugger = "0.7.16"
LinearAlgebra = "1.12.0"
Nemo = "0.53.1"
Profile = "1.11.0"
PythonCall = "0.9.31"
Revise = "3.12.3"
Test = "1.11.0"
